repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.0
    hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python ]
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python ]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    -   id: mypy
        args: [--enable-incomplete-feature=Unpack, --ignore-missing-imports, --explicit-package-bases]
        additional_dependencies: [tqdm-stubs, types-requests, types-ujson]