site_name: Brightband Common Python Library
theme:
  name: "material"
  logo: "assets/images/Brightband-Symbol-Alabaster.svg"
  favicon: "assets/images/Brightband-Symbol-Alabaster.svg"
  palette:
    scheme: "brightband"
extra_css:
  - stylesheets/brightband.css
nav:
  - Home: index.md
plugins:
- search
- mkdocs-autoapi:
    autoapi_dir: src
- mkdocstrings:
    handlers:
      python:
        paths: [src]
        options:
          docstring_style: google
          docstring_options:
            ignore_init_summary: true
          merge_init_into_class: true
          group_by_category: true
          # show_category_heading: true
          docstring_section_style: list
          show_source: false
          separate_signature: true
          signature_crossrefs: true
          summary: true