site_name: NNJA-AI Software Development Kit
site_description: >-
  Python SDK for the AI-optimized NOAA NASA Joint Archive (NNJA) of Observations for Earth System Reanalysis.
site_author: Brightband PBC
# site_url: https:/nnja-io.brightband.com
repo_url: https://github.com/brightbandtech/nnja-ai
repo_name: brightbandtech/nnja-ai
copyright: Brightband PBC

# strict: true  # Disable during dev

theme:
  name: material
  logo: assets/images/Brightband-Symbol-Alabaster.svg
  favicon: assets/images/Brightband-Symbol-Alabaster.svg
  palette:
    scheme: "brightband"

extra_css:
  - stylesheets/brightband.css

plugins:
  - search
  - mkdocs-jupyter
  - mkdocs-autoapi:
      autoapi_dir: src
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            group_by_category: true
            # show_category_heading: true
            docstring_section_style: list
            show_source: false
            separate_signature: true
            signature_crossrefs: true
            summary: true

nav:
  - Home: index.md
  - Data:
    - Datasets: datasets.md
    - Understanding the Data: understanding-the-data.md
  - Example Notebooks:
    - Basic Dataset Example: example_notebooks/basic_dataset_example.ipynb
    - Dataset Overview: example_notebooks/dataset_overview.ipynb
    - ADPSFC (weather station) Example: example_notebooks/adpsfc_example.ipynb
    - ADPUPA (radiosonde) Profile Example: example_notebooks/adpupa_profile_example.ipynb

  - FAQ: faq.md
